routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//=====================Front end===============================
Route::get('/','HomeController@index');
Route::get('search','HomeController@searchResult')->name('search.result');
Route::get('search/{category}','HomeController@searchFertilityClinicResult')->name('search.fertility-clicnic.result');
Route::get('category/search/{category?}','HomeController@showSearchForm')->name('search.form');

Route::get('member/{becomeMember}','HomeController@singleMemberDetails')->name('single.member');
Route::get('fertility-clinics/{fertilityClinicMember}','HomeController@singleClinicMemberDetails')->name('single.clinic.member');

//======================Admin Dashboard==================================
Route::group(['prefix'=>'admin-en'],function(){

	//===================Menus Management===========================
	Route::resource('menus','MenuController');
	Route::get('menus/delete/{menu}','MenuController@destroy')->name('menus.destroy');

	//=======================Pages Management==========================
	Route::resource('pages','PageController');
	Route::get('page/create/new','PageController@create')->name('pages.create');
	Route::get('pages/delete/{page}','PageController@destroy')->name('pages.destroy');

	//=======================Sub Pages Management==========================
	Route::resource('subpages','SubPageController');
	Route::get('subpage/create/new','SubPageController@create')->name('subpages.create');
	Route::get('subpages/delete/{subpage}','SubPageController@destroy')->name('subpages.destroy');



	

	//========================intended parents================================
	Route::resource('intended_parents','IntendedParentController');
	Route::get('intended_parents/delete/{intendedParent}','IntendedParentController@destroy')->name('intended_parents.destroy');
	Route::get('all-email','IntendedParentController@allEmails')->name('all.emails');
	//emails export
	Route::get('export/emails','IntendedParentController@exportEmails')->name('export.emails');
	//==========================Reviews=========================================
		
	//======================Scouts Management===================================
	Route::resource('scouts','ScoutController');
	Route::get('scouts/destroy/{scout}','ScoutController@destroy')->name('scouts.destroy');

	//============================Website Settings======================================
	Route::resource('settings','SettingController',['only'=>['index','update']]);
	

});

//==============================================================================
		// m.tuifertility.com (members management admin dashboard)
//==============================================================================

Route::group(['prefix'=>'m.tuifertility/admin-en'],function(){
	//===============admin side become a member========================

	Route::resource('become_members','BecomeMemberController',['except'=>['index']]);
	Route::get('become_members/category/{category}','BecomeMemberController@index')->name('become_members.index');
	Route::get('become_members/show/{becomeMember}','BecomeMemberController@show')->name('become_members.show');
	Route::get('become_members/delete/{becomeMember}','BecomeMemberController@destroy')->name('become_members.destroy');
	Route::get('become-a-member/verify/{becomeMember}','BecomeMemberController@verifyMember')->name('become_members.verify');

//===================Become fertility member routes====================
	Route::resource('fertility_clinic_members','FertilityClinicMemberController');
	Route::get('become-clinic-member/verify/{fertilityClinicMember}','FertilityClinicMemberController@verifyMember')->name('become_fertility_members.verify');
	Route::get('fertility_clinic_members/delete/{fertilityClinicMember}','FertilityClinicMemberController@destroy')->name('fertility_clinic_members.destroy');

	//===================Menus Management===========================
	Route::resource('menus','MemberSiteMenuController',['names'=>[
		'index' => 'member.menus.index',
		'store' => 'member.menus.store',
		'update' => 'member.menus.update',
		'edit' => 'member.menus.edit',
	]]);
	Route::get('menus/delete/{menu}','MenuController@destroy')->name('member.menus.destroy');

	//=======================Pages Management==========================
	Route::resource('pages','MemberSitePageController',['names'=>[
		'index' => 'member.pages.index',
		'store' => 'member.pages.store',
		'update' => 'member.pages.update',
		'edit' => 'member.pages.edit',
	],'except'=>['create','destroy']]);
	Route::get('page/create/new','MemberSitePageController@create')->name('member.pages.create');
	Route::get('pages/delete/{page}','MemberSitePageController@destroy')->name('member.pages.destroy');

	//=======================Sub Pages Management==========================
	Route::resource('subpages','MemberSiteSubPageController',['names'=>[
		'index' => 'member.subpages.index',
		'store' => 'member.subpages.store',
		'update' => 'member.subpages.update',
		'edit' => 'member.subpages.edit',
	],'except'=>['create','destroy']]);
	Route::get('subpage/create/new','MemberSiteSubPageController@create')->name('member.subpages.create');
	Route::get('subpages/delete/{subpage}','MemberSiteSubPageController@destroy')->name('member.subpages.destroy');

	//=======================Pages Text========================================
	Route::get('all-pages','MemberFormPageTextController@allPages')->name('all.pages');
	// become member form page text management
	Route::get('form-text-page/{category}','MemberFormPageTextController@edit')->name('member.form.edit');
	Route::put('form-text-page/{memberFormPageText}','MemberFormPageTextController@update')->name('member.form.update');
	Route::put('clinic-form-text-page/{clinicFormPageText}','MemberFormPageTextController@clinicUpdate')->name('clinic.member.form.update');

	//Apply Now buttons text
	Route::get('apply-now-buttons','MemberFormPageTextController@editApplyNowButtons')->name('apply.now.buttons');
	Route::put('apply-now-buttons/{applyNowButton}','MemberFormPageTextController@updateApplyNowButtons')->name('applynow.button.update');

});

//================Become a member Routes===========================
Route::group(['prefix'=>'m.tuifertility'],function(){
	Route::get('become-a-member/signup','BecomeMemberController@SelectForm');
	Route::get('become-member/{category}','HomeController@becomeMember')->name('become.member');
	Route::post('become-member/applied','BecomeMemberController@store')->name('member.store');
});
	//=========================End become member routes====================

//======================Become Intended parent route======================
	Route::get('intended-parent/sign-up/{category}','HomeController@intendedParentForm')->name('intendent.parent.form');



Route::get('admin-en', function () {
    return view('admin-dashboard.layouts.master');
});
Route::get('m.tuifertility/admin-en', function () {
    return view('member-admin-dashboard.layouts.master');
});


Route::get('thank-you','HomeController@thankyou')->name('thankyou');
Route::get('{menu}/{page}','HomeController@showPage');
Route::get('{menu}/{page}/{subpage}','HomeController@showSubPage');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

resources/views/front-end/partials/become-fertility-clinic.blade.php
@extends('front-end.layouts.member-master')
@section('content')
<section class="banner padding-top-200px padding-bottom-30px sm-ptb-0px" style="background-image: url({{asset('assets/img/banner_1.jpg')}});">
   <div id="page-title" class="margin-mob">
      <div class="container">
         <ol class="breadcrumb opacity-5">
            <li><a href="#">Home</a></li>
            <li class="active">Sing Up</li>
         </ol><br>
         <h1 class="font-weight" style="color: #007cff;">
            {{$formText->title}}
         </h1><br>
         <p style="font: 14px/26px Raleway; line-height: 26px; color: #6b6c6c; line-height: 24px;"><em>{{$formText->note}}</em></p>
         @if ($errors->any())
         <div class="alert alert-danger">
            <ul>
               @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
               @endforeach
            </ul>
         </div>
         @endif
      </div>
   </div>
   <hr>
   <div class="">
      <div class="container margin-bottom-0px">
         <!--======= log_in_page =======-->
         <div id="log-in" class=" .padding-top-10 site-form border-radius-10">
            <div class="form-output">
               <form method="post" action="{{route('fertility_clinic_members.store')}}" enctype="multipart/form-data">
                  @csrf
                  <input type="hidden" name="category" value="{{$category}}">
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->clinic_name}}</label>
                           <input class="form-control" placeholder="" name="clinic_name" type="text" value="{{old('clinic_name')}}">
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->email}}</label>
                           <input class="form-control" name="email" placeholder="" type="email" value="{{old('email')}}">
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->name}}</label>
                           <input class="form-control" name="name" placeholder="" type="text" value="{{old('name')}}">
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->country}}</label>
                           <select class="selectpicker form-control" name="country">
                              <option value="">Please Select {{$formText->country}}</option>
                              @foreach($countries as $country)
                              <option value="{{$country->country_name}}">{{$country->country_name}}</option>
                              @endforeach
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->address}}</label>
                           <input class="form-control" name="address" placeholder="{{$formText->address}}" type="text" value="{{old('address')}}">
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->phone}}</label>
                           <input class="form-control" name="phone" placeholder="{{$formText->phone}}" type="text" value="{{old('phone')}}">
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->website}}</label>
                           <input class="form-control" name="website" placeholder="" type="text" value="{{old('website')}}">
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->provide_services_for}}</label>
                           <div class="input-group">
                              <select class="selectpicker form-control jq_multiselect" enable_select_all="false" multiple="multiple" name="provide_services_for[]" required>
                                 @foreach(explode(',',$formText->provide_services_for_data) as $key => $provide_services_for_data)
                              <option value="{{$provide_services_for_data}}">{{$provide_services_for_data}}</option>
                              @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->treatments}}</label>
                           <div class="input-group">
                              <select class="selectpicker form-control jq_multiselect" multiple="multiple" enable_select_all="false" required  name="treatments[]">
                                 @foreach(explode(',',$formText->treatments_data) as $key => $treatments_data)
                              <option value="{{$treatments_data}}">{{$treatments_data}}</option>
                              @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->willing_to_assist}}</label>
                           <div class="input-group">
                              <select class="selectpicker form-control spoken_language jq_multiselect" name="willing_to_assist[]" required multiple="multiple">
                                 @foreach(explode(',',$formText->willing_to_assist_data) as $key => $willing_to_assist_data)
                              <option value="{{$willing_to_assist_data}}">{{$willing_to_assist_data}}</option>
                              @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->providing_service}}</label>
                           <div class="input-group">
                              <select class="selectpicker form-control spoken_language jq_multiselect" name="providing_service[]" multiple="multiple">
                                @foreach(explode(',',$formText->providing_service_data) as $key => $providing_service_data)
                              <option value="{{$providing_service_data}}">{{$providing_service_data}}</option>
                              @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating is-select">
                           <label class="control-label">{{$formText->willing_to_assist_countries}}</label>
                           <div class="input-group">
                              <select class="selectpicker form-control spoken_language jq_multiselect" name="willing_to_assist_countries[]" multiple="multiple">
                                 @foreach($countries as $country)
                                 <option value="{{$country->country_name}}">{{$country->country_name}}</option>
                                 @endforeach
                              </select>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->describe_clinic}}</label>
                           <textarea class="form-control" name="describe_clinic" placeholder="" rows="6" style="height: 100px;">{{old('describe_clinic')}}</textarea>
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->video_url}}</label>
                           <textarea class="form-control" name="video_url" type="text" style="height: 100px;" value="{{old('video_url')}}"></textarea>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="form-group label-floating">
                           <label class="control-label">{{$formText->pictures}}</label><br>
                           <!-- <input class="form-control" type="file" multiple="multiple" name="pictures[]" placeholder=""> -->
                           <span class="btn btn-success btn-success2 fileinput-button">
                              <i class="fa fa-plus"></i>
                              <span>{{$formText->add_file}}</span>
                              <input type="file" name="pictures[]" multiple="multiple">
                           </span>
                        </div>
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-6 col-sm-12">
                        <div class="g-recaptcha"
                           data-sitekey="{{env('GOOGLE_RECAPTCHA_KEY','6LeP3eMUAAAAAE1Nk-Z2v-JGxUUwwOfRzPwzRifL')}}">
                        </div>
                     </div>
                  </div>
                  <div class="row" style="margin-top: 10px;">
                     <div class="col-md-12">
                        <button type="submit" class="search_btn btn btn-block">{{$formText->complete_signup}}</button>
                     </div>
                  </div>
               </form>
            </div>
         </div>
         <!--======= // log_in_page =======-->
      </div>
      <!-- <div class="container col-md-6">
         <img src="{{asset('assets/img/banner-11.jpg')}}">
         
         </div> -->
   </div>
</section>
@endsection
@section('additional-js')
<script type="text/javascript" src="{{asset('assets/assets/bootstrap-datepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/assets/bootstrap-datepicker.init.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/assets/signup.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/assets/bootstrap-multiselect.js')}}"></script>
<link rel="stylesheet" type="text/css" href="{{asset('assets/assets/datepicker3.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/assets/bootstrap-multiselect.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assets/assets/member_generic.css')}}">
<script src='https://www.google.com/recaptcha/api.js'></script>
@endsection

resources/views/front-end/partials/blog.blade.php
<section class="padding-tb-100px background-grey-1">
        <div class="container">
            <!-- Title -->
            <div class="row justify-content-center margin-bottom-45px">
                <div class="col-lg-10">
                    <div class="row">
                        <div class="col-md-3 wow fadeInUp">
                            <h1 class="text-second-color font-weight-300 text-sm-center text-lg-right margin-tb-15px">Our Blog</h1>
                        </div>
                        <div class="col-md-7 wow fadeInUp" data-wow-delay="0.2s">
                            <p class="text-grey-2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                        </div>
                        <div class="col-md-2 wow fadeInUp" data-wow-delay="0.4s">
                            <a href="#" class="text-main-color margin-tb-15px d-inline-block"><span class="d-block float-left margin-right-10px margin-top-5px">Show All</span> <i class="far fa-arrow-alt-circle-right text-large margin-top-7px"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // Title -->

            <div class="row">
                <div class="col-lg-6 sm-mb-45px">
                    <div class="background-white thum-hover box-shadow hvr-float full-width wow fadeInUp">
                        <div class="float-md-left margin-right-30px thum-xs">
                            <img src="{{asset('assets/img/blog-1.jpg')}}" alt="">
                        </div>
                        <div class="padding-25px">
                            <i class="far fa-folder-open text-main-color"></i>
                            <a href="#" class="text-main-color">News </a> ,
                            <a href="#" class="text-main-color">Articles </a>
                            <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                            <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                            <span class="text-extra-small d-block d-sm-none"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="col-lg-6 sm-mb-45px">
                    <div class="background-white thum-hover box-shadow hvr-float full-width wow fadeInUp">
                        <div class="float-md-left margin-right-30px thum-xs">
                            <img src="{{asset('assets/img/blog-2.jpg')}}" alt="">
                        </div>
                        <div class="padding-25px">
                            <i class="far fa-folder-open text-main-color"></i>
                            <a href="#" class="text-main-color">News </a> ,
                            <a href="#" class="text-main-color">Articles </a>
                            <h3><a href="#" class="d-block text-dark text-capitalize text-medium margin-tb-15px">Long Don’t Spend Time Beating On a Wall, Hoping To Trans ... </a></h3>
                            <span class="margin-right-20px text-extra-small"><i class="far fa-user text-grey-2"></i> By : <a href="#"> Rabie Elkheir</a></span>
                            <span class="text-extra-small d-block d-sm-none"><i class="far fa-clock text-grey-2"></i> Date :  <a href="#"> July 15, 2016</a></span>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

        </div>
    </section>

resources/views/front-end/partials/famous-donors.blade.php
 <section class="padding-tb-100px background-grey-1">
        <div class="container">
            <!-- Title -->
            <div class="row justify-content-center margin-bottom-45px">
                <div class="col-lg-10">
                    <div class="row">
                        <div class="col-md-4 wow fadeInUp">
                            <h1 class="text-second-color font-weight-300 text-sm-center text-lg-right margin-tb-15px">Famous Doctors</h1>
                        </div>
                        <div class="col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                            <p class="text-grey-2">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
                        </div>
                        <div class="col-md-2 wow fadeInUp" data-wow-delay="0.4s">
                            <a href="#" class="text-main-color margin-tb-15px d-inline-block"><span class="d-block float-left margin-right-10px margin-top-5px">Show All</span> <i class="far fa-arrow-alt-circle-right text-large margin-top-7px"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // Title -->

            <div class="row">

                <!-- Doctor -->
                <div class="col-lg-3 col-md-6 hvr-bob sm-mb-45px">
                    <div class="background-white box-shadow wow fadeInUp" data-wow-delay="0.2s">
                        <div class="thum">
                            <a href="#"><img src="{{asset('assets/img/doctor-1.jpg')}}" alt=""></a>
                        </div>
                        <div class="padding-30px">
                            <span class="text-grey-2">Internal</span>
                            <h5 class="margin-tb-15px"><a class="text-dark" href="#">Dr. Shahrzat Moh</a></h5>
                            <div class="rating clearfix">
                                <ul class="float-left">
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li></li>
                                </ul>
                                <small class="float-right text-grey-2">(17 reviews)</small>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // Doctor -->

                <!-- Doctor -->
                <div class="col-lg-3 col-md-6 hvr-bob sm-mb-45px">
                    <div class="background-white box-shadow wow fadeInUp" data-wow-delay="0.4s">
                        <div class="thum">
                            <a href="#"><img src="{{asset('assets/img/doctor-2.jpg')}}" alt=""></a>
                        </div>
                        <div class="padding-30px">
                            <span class="text-grey-2">Internal</span>
                            <h5 class="margin-tb-15px"><a class="text-dark" href="#">Dr. Adwa Ali</a></h5>
                            <div class="rating clearfix">
                                <ul class="float-left">
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li></li>
                                </ul>
                                <small class="float-right text-grey-2">(17 reviews)</small>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // Doctor -->

                <!-- Doctor -->
                <div class="col-lg-3 col-md-6 hvr-bob sm-mb-45px">
                    <div class="background-white box-shadow wow fadeInUp" data-wow-delay="0.6s">
                        <div class="thum">
                            <a href="#"><img src="{{asset('assets/img/doctor-3.jpg')}}" alt=""></a>
                        </div>
                        <div class="padding-30px">
                            <span class="text-grey-2">Internal</span>
                            <h5 class="margin-tb-15px"><a class="text-dark" href="#">Dr. Salma Elkheir</a></h5>
                            <div class="rating clearfix">
                                <ul class="float-left">
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li></li>
                                </ul>
                                <small class="float-right text-grey-2">(17 reviews)</small>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // Doctor -->

                <!-- Doctor -->
                <div class="col-lg-3 col-md-6 hvr-bob sm-mb-45px">
                    <div class="background-white box-shadow wow fadeInUp" data-wow-delay="0.8s">
                        <div class="thum">
                            <a href="#"><img src="{{asset('assets/img/doctor-4.jpg')}}" alt=""></a>
                        </div>
                        <div class="padding-30px">
                            <span class="text-grey-2">Internal</span>
                            <h5 class="margin-tb-15px"><a class="text-dark" href="#">Dr. Salim Qasim</a></h5>
                            <div class="rating clearfix">
                                <ul class="float-left">
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li class="active"></li>
                                    <li></li>
                                </ul>
                                <small class="float-right text-grey-2">(17 reviews)</small>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // Doctor -->

            </div>
        </div>
    </section>