routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//=====================Front end===============================
Route::get('/','HomeController@index');
Route::get('search','HomeController@searchResult')->name('search.result');
Route::get('search/{category}','HomeController@searchFertilityClinicResult')->name('search.fertility-clicnic.result');
Route::get('category/search/{category?}','HomeController@showSearchForm')->name('search.form');

Route::get('member/{becomeMember}','HomeController@singleMemberDetails')->name('single.member');
Route::get('fertility-clinics/{fertilityClinicMember}','HomeController@singleClinicMemberDetails')->name('single.clinic.member');

//======================Admin Dashboard==================================
Route::group(['prefix'=>'admin-en'],function(){

	//===================Menus Management===========================
	Route::resource('menus','MenuController');
	Route::get('menus/delete/{menu}','MenuController@destroy')->name('menus.destroy');

	//=======================Pages Management==========================
	Route::resource('pages','PageController');
	Route::get('page/create/new','PageController@create')->name('pages.create');
	Route::get('pages/delete/{page}','PageController@destroy')->name('pages.destroy');

	//=======================Sub Pages Management==========================
	Route::resource('subpages','SubPageController');
	Route::get('subpage/create/new','SubPageController@create')->name('subpages.create');
	Route::get('subpages/delete/{subpage}','SubPageController@destroy')->name('subpages.destroy');



	

	//========================intended parents================================
	Route::resource('intended_parents','IntendedParentController');
	Route::get('intended_parents/delete/{intendedParent}','IntendedParentController@destroy')->name('intended_parents.destroy');
	Route::get('all-email','IntendedParentController@allEmails')->name('all.emails');
	//emails export
	Route::get('export/emails','IntendedParentController@exportEmails')->name('export.emails');
	//==========================Reviews=========================================
		
	//======================Scouts Management===================================
	Route::resource('scouts','ScoutController');
	Route::get('scouts/destroy/{scout}','ScoutController@destroy')->name('scouts.destroy');

	//============================Website Settings======================================
	Route::resource('settings','SettingController',['only'=>['index','update']]);
	

});

//==============================================================================
		// m.tuifertility.com (members management admin dashboard)
//==============================================================================

Route::group(['prefix'=>'m.tuifertility/admin-en'],function(){
	//===============admin side become a member========================

	Route::resource('become_members','BecomeMemberController',['except'=>['index']]);
	Route::get('become_members/category/{category}','BecomeMemberController@index')->name('become_members.index');
	Route::get('become_members/show/{becomeMember}','BecomeMemberController@show')->name('become_members.show');
	Route::get('become_members/delete/{becomeMember}','BecomeMemberController@destroy')->name('become_members.destroy');
	Route::get('become-a-member/verify/{becomeMember}','BecomeMemberController@verifyMember')->name('become_members.verify');

//===================Become fertility member routes====================
	Route::resource('fertility_clinic_members','FertilityClinicMemberController');
	Route::get('become-clinic-member/verify/{fertilityClinicMember}','FertilityClinicMemberController@verifyMember')->name('become_fertility_members.verify');
	Route::get('fertility_clinic_members/delete/{fertilityClinicMember}','FertilityClinicMemberController@destroy')->name('fertility_clinic_members.destroy');

	//===================Menus Management===========================
	Route::resource('menus','MemberSiteMenuController',['names'=>[
		'index' => 'member.menus.index',
		'store' => 'member.menus.store',
		'update' => 'member.menus.update',
		'edit' => 'member.menus.edit',
	]]);
	Route::get('menus/delete/{menu}','MenuController@destroy')->name('member.menus.destroy');

	//=======================Pages Management==========================
	Route::resource('pages','MemberSitePageController',['names'=>[
		'index' => 'member.pages.index',
		'store' => 'member.pages.store',
		'update' => 'member.pages.update',
		'edit' => 'member.pages.edit',
	],'except'=>['create','destroy']]);
	Route::get('page/create/new','MemberSitePageController@create')->name('member.pages.create');
	Route::get('pages/delete/{page}','MemberSitePageController@destroy')->name('member.pages.destroy');

	//=======================Sub Pages Management==========================
	Route::resource('subpages','MemberSiteSubPageController',['names'=>[
		'index' => 'member.subpages.index',
		'store' => 'member.subpages.store',
		'update' => 'member.subpages.update',
		'edit' => 'member.subpages.edit',
	],'except'=>['create','destroy']]);
	Route::get('subpage/create/new','MemberSiteSubPageController@create')->name('member.subpages.create');
	Route::get('subpages/delete/{subpage}','MemberSiteSubPageController@destroy')->name('member.subpages.destroy');

	//=======================Pages Text========================================
	Route::get('all-pages','MemberFormPageTextController@allPages')->name('all.pages');
	// become member form page text management
	Route::get('form-text-page/{category}','MemberFormPageTextController@edit')->name('member.form.edit');
	Route::put('form-text-page/{memberFormPageText}','MemberFormPageTextController@update')->name('member.form.update');
	Route::put('clinic-form-text-page/{clinicFormPageText}','MemberFormPageTextController@clinicUpdate')->name('clinic.member.form.update');

	//Apply Now buttons text
	Route::get('apply-now-buttons','MemberFormPageTextController@editApplyNowButtons')->name('apply.now.buttons');
	Route::put('apply-now-buttons/{applyNowButton}','MemberFormPageTextController@updateApplyNowButtons')->name('applynow.button.update');

});

//================Become a member Routes===========================
Route::group(['prefix'=>'m.tuifertility'],function(){
	Route::get('become-a-member/signup','BecomeMemberController@SelectForm');
	Route::get('become-member/{category}','HomeController@becomeMember')->name('become.member');
	Route::post('become-member/applied','BecomeMemberController@store')->name('member.store');
});
	//=========================End become member routes====================

//======================Become Intended parent route======================
	Route::get('intended-parent/sign-up/{category}','HomeController@intendedParentForm')->name('intendent.parent.form');



Route::get('admin-en', function () {
    return view('admin-dashboard.layouts.master');
});
Route::get('m.tuifertility/admin-en', function () {
    return view('member-admin-dashboard.layouts.master');
});


Route::get('thank-you','HomeController@thankyou')->name('thankyou');
Route::get('{menu}/{page}','HomeController@showPage');
Route::get('{menu}/{page}/{subpage}','HomeController@showSubPage');

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

resources/views/admin-dashboard/members-management/intended-parent-members/all-emails.blade.php
@extends('admin-dashboard.layouts.master')
@section('additional-head')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
@endsection
@section('content')
<hr>
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<h2>All Intended Parent Emails</h2><span>(Applied to use Surrogate Mothers, Sperm Donors, Egg Donors)</span>
<a href="{{route('export.emails')}}" class="btn btn-primary" style="float: right;">Export All Emails</a>
<table class="table table-hover" id="myTable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
  	@php $i=1; @endphp
    	@foreach($emails as $email)
    <tr>
      <th scope="row">{{$i}}</th>
      <td>{{$email->email}}</td>
    </tr>
    @php $i++; @endphp
      @endforeach
  </tbody>
</table>
@endsection
@section('additional-js')
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
  $(document).ready( function () {
    $('#myTable').DataTable({
      "lengthMenu": [[100, 200, 300, -1], [100, 200, 300, "All"]]
    });
} );
</script>
@endsection

resources/views/admin-dashboard/members-management/intended-parent-members/all-intended-parents.blade.php
@extends('admin-dashboard.layouts.master')
@section('additional-head')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
@endsection
@section('content')
<hr>
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<h2>Intended Parents</h2><span>(Applied to use Surrogate Mothers, Sperm Donors, Egg Donors)</span>
<table class="table table-hover" id="myTable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Full Name</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  	@php $i=1; @endphp
    	@foreach($members as $member)
    <tr>
      <th scope="row">{{$i}}</th>
      <td>{{$member->email}}</td>
      <td>{{$member->name}}</td>
      <td>{{$member->category}}</td>
      <td>{{$member->status==1 ? 'Verified':'Not Verified'}}</td>
      <td>
        <a href="{{route('intended_parents.show',$member->id)}}" title="Show Member Details"><i class="fa fa-eye"></i></a>
      	<a href="{{route('intended_parents.destroy',$member->id)}}" onclick="return confirm('Are you sre to delete the record ?')" title="Delete Member"><i class="fa fa-trash"></i></a>
      </td>
    </tr>
    @php $i++; @endphp
      @endforeach
  </tbody>
</table>
@endsection
@section('additional-js')
<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
  $(document).ready( function () {
    $('#myTable').DataTable({
      "lengthMenu": [[100, 200, 300, -1], [100, 200, 300, "All"]]
    });
} );
</script>
@endsection

resources/views/admin-dashboard/members-management/intended-parent-members/single-intended-parent-details.blade.php
@extends('admin-dashboard.layouts.master')
@section('additional-head')
<!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> -->
@endsection
@section('content')
<!-- Page Title -->
                <div id="page-title" class="padding-30px background-white full-width">
                    <div class="container">
                        <ol class="breadcrumb opacity-5">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Member Details Page</a></li>
                        </ol>
                        <h1 class="font-weight-300">Member Details Page</h1>
                    </div>
                </div>
                <!-- // Page Title -->

                <div class="margin-tb-45px full-width">
                    <div class="padding-30px background-white border-radius-20 box-shadow">
                        <h3><i class="far fa-list-alt margin-right-10px text-main-color"></i> {{$intendedParent->name}}'s Detailed Information </h3>
                        <hr>
                        <form method="post" action="#" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" name="category" value="{{$intendedParent->category}}">
                     <div class="form-group label-floating">
                        
                        <img src="{{asset('storage/'.$intendedParent->picture)}}"   height="100">
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Your Email*</label>
                        <input class="form-control" selected value="{{$intendedParent->email}}" placeholder="" name="email" type="email">
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Name</label>
                        <input class="form-control" selected value="{{$intendedParent->name}}" name="name" placeholder="" type="text">
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Birthday (mo/day/yr)*</label>
                        <input class="form-control" selected value="{{$intendedParent->birthday}}" type="date">
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Country</label>
                        <select class="selectpicker form-control" name="country">
                          
                          <option value="{{$intendedParent->country}}" selected>{{$intendedParent->country}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Address</label>
                        <input class="form-control" selected value="{{$intendedParent->address}}"  type="text">
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Phone/WhatsApp/Viber/Telegram</label>
                        <input class="form-control" selected value="{{$intendedParent->phone}}" type="text">
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Nationality*</label>
                        <select class="selectpicker form-control" name="nationality">
                              <option selected value="{{$intendedParent->nationality}}">{{$intendedParent->nationality}}</option> 
                       </select>
                    </div>

                    <div class="form-group label-floating is-select">
                        <label class="control-label">Race</label>
                        <select class="selectpicker form-control" name="race">
                           <option selected value="{{$intendedParent->race}}">{{$intendedParent->race}}</option>
                       </select>
                    </div>

                    <div class="form-group label-floating is-select">
                        <label class="control-label">Religion</label>
                        <select class="selectpicker form-control" name="religion">
                           <option selected value="{{$intendedParent->religion}}">{{$intendedParent->religion}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Education</label>
                        <select class="selectpicker form-control" name="education">
                           <option selected value="{{$intendedParent->education}}">{{$intendedParent->education}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Smoker</label>
                        <select class="selectpicker form-control" name="smoker">
                            <option >{{$intendedParent->smoker==1?'Yes':'No'}}</option>
                       </select>
                    </div>
                    
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Willing To Travel</label>
                        <select class="selectpicker form-control" name="willing_to_travel">
                            <option selected value="{{$intendedParent->willing_to_travel}}">{{$intendedParent->willing_to_travel}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Number of Children(non-donor)</label>
                        <select class="selectpicker form-control" name="number_of_children">
                            <option selected value="{{$intendedParent->number_of_children}}">{{$intendedParent->number_of_children}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Number of Surrogate Children</label>
                        <select class="selectpicker form-control" name="number_of_surrogate_children">
                            <option selected value="{{$intendedParent->number_of_surrogate_children}}">{{$intendedParent->number_of_surrogate_children}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Have you had a Surrogate/Donor before?</label>
                        <select class="selectpicker form-control" name="given_service_before">
                            <option selected value="{{$intendedParent->had_surrogate_before}}">{{$intendedParent->had_surrogate_before}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Marital Status</label>
                        <select class="selectpicker form-control" name="marital_status">
                            <option selected value="{{$intendedParent->marital_status}}">{{$intendedParent->marital_status}}</option>
                       </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Spoken Languages</label>
                        <select class="selectpicker form-control" name="spoken_language">
                        <option selected value="{{$intendedParent->spoken_language}}">{{$intendedParent->spoken_language}}</option>
                    </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">What is your budget for surrogacy/donor expenses?</label>
                        <select class="selectpicker form-control" name="budget">
                          <option selected value="{{$intendedParent->budget}}">{{$intendedParent->budget}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Looking to Connect With</label>
                        <select class="selectpicker form-control" name="looking_to_connect_with">
                          <option selected value="{{$intendedParent->looking_to_connect_with}}">{{$intendedParent->looking_to_connect_with}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">Explain Your Couple Type</label>
                        <select class="selectpicker form-control" name="your_couple_type">
                          <option selected value="{{$intendedParent->your_couple_type}}">{{$intendedParent->your_couple_type}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">You prefer Surrogates/Donors between the ages of?</label>
                        <select class="selectpicker form-control" name="prefer_surrogate_age">
                          <option selected value="{{$intendedParent->prefer_surrogate_age}}">{{$intendedParent->prefer_surrogate_age}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">You prefer Surrogates/Donors from which country?</label>
                        <select class="selectpicker form-control" name="prefer_surrogate_country">
                          <option selected value="{{$intendedParent->prefer_surrogate_country}}">{{$intendedParent->prefer_surrogate_country}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating is-select">
                        <label class="control-label">You prefer Surrogates/Donors from which nationality?</label>
                        <select class="selectpicker form-control" name="prefer_surrogate_nationality">
                          <option selected value="{{$intendedParent->prefer_surrogate_nationality}}">{{$intendedParent->prefer_surrogate_nationality}}</option>
                        </select>
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">How would you best describe yourself?</label>
                        <textarea class="form-control" name="describe_yourself" >{{$intendedParent->describe_yourself}}</textarea>
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Explain your reasons for wanting a surrogate/donor</label>
                        <textarea class="form-control" name="reason_for_wanting_surrogate" >{{$intendedParent->reason_for_wanting_surrogate}}</textarea>
                    </div>
                    <div class="form-group label-floating">
                        <label class="control-label">Use this space to communicate a letter to potential Surrogate/Donor.</label>
                        <textarea class="form-control" name="communication_letter">{{$intendedParent->communication_letter}}</textarea>
                    </div>
                   
                </div>
                <a href="{{url()->previous()}}" class="btn btn-lg border-2  btn-primary btn-block border-radius-15 padding-15px box-shadow">Return Back</a>
            </form>
                
@endsection
@section('additional-js')
<!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote.min.js"></script>
 <script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>
@endsection